apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: applications.ones.xiaohongshu.com
spec:
  group: ones.xiaohongshu.com
  version: v1
  names:
    kind: Application
    plural: applications
  scope: Namespaced
