apiVersion: xiaohongshu.com/v1
kind: Application
metadata:
  name: edith
spec:
  template: "shequ-java"
  owner: "liuding@xiaohongshu.com"
  public: true
  childApps:
    - name: "edith-sit-adchips"
      controller: "deployment"
    - name: "edith-sit-stable"
      controller: "statefulset"
