apiVersion: xiaohongshu.com/v1
kind: Application
metadata:
  name: cnp-web-console
spec:
  template: "shequ-java"
  owner: "lvjin@cmss.chinamobile.com"
  public: true
  imageRepository: cnp/kubesphere
  imageName: cnp-web-console
  namespace: cnp-web-console
  gitAddr: "git@code.devops.xiaohongshu.com:devops/ones.git"
  childApps:
    - name: "cnp-web-console"
      controller: "deployment"
      type: "Service"
      yaml: ""
      resources:
        - name: cnp-web-console
          type: deployment
          cluster: sit
